version: "3.4"

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local

services:
  graphql:
    image: "gregorip02/laravel-fpm"
    container_name: "graphql"
    working_dir: /opt/app
    volumes:
      - $PWD:/opt/app
    ports:
      - "8080:80"
    networks:
      - "app-network"
    # TODO: add a default.conf file and remove the next line
    command: /bin/sh -c "rm -rf /var/www/html && ln -fs /opt/app/public /var/www/html && /sbin/runit-wrapper"
    depends_on:
      - "mysql"

  mysql:
    image: "mysql:5.7"
    container_name: "storage"
    volumes:
      - "app-data:/var/lib/mysql"
    networks:
      - "app-network"
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
